import type { Metadata } from "next";
import { ContactForm } from "@/components/contact/contact-form";
import { createPageMetadata } from "@/lib/seo";

export const metadata: Metadata = createPageMetadata("Contact", "Contact Dhaka-based photographer TA Shanto for photography assignments, collaborations and print enquiries.", "/contact");

export default function ContactPage() {
  return <div className="mx-auto max-w-[112rem] px-[var(--space-page)] pb-36 pt-[clamp(8rem,14vw,12rem)]"><header className="mb-20 grid grid-cols-[minmax(11rem,1fr)_2fr] gap-8 max-md:grid-cols-1"><p className="text-xs uppercase tracking-[.2em] text-[var(--muted)]">Get in touch</p><h1 className="m-0 font-[family-name:var(--serif)] text-[clamp(4rem,7vw,8rem)] leading-[.86] tracking-[-.05em]">Let’s make<br /><em>something lasting.</em></h1><span className="col-start-2 max-w-md text-[var(--muted)] max-md:col-start-1">For assignments, collaborations, print enquiries, or simply to say hello.</span></header><div className="grid grid-cols-[.8fr_1.2fr] gap-[clamp(4rem,10vw,12rem)] max-md:grid-cols-1"><div className="space-y-10"><div className="grid"><small className="mb-2 uppercase tracking-widest text-[var(--muted)]">Email</small><a className="font-[family-name:var(--serif)] text-2xl" href="mailto:hello@tashanto.com">hello@tashanto.com</a></div><div className="grid gap-2"><small className="mb-2 uppercase tracking-widest text-[var(--muted)]">Elsewhere</small><a href="https://instagram.com/iamtashanto" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://twitter.com/iamtashanto" target="_blank" rel="noreferrer">Twitter ↗</a><a href="https://facebook.com/iamtashanto" target="_blank" rel="noreferrer">Facebook ↗</a><a href="https://youtube.com/@iamtashanto" target="_blank" rel="noreferrer">YouTube ↗</a><a href="https://linkedin.com/in/iamtashanto" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://tashanto.com" target="_blank" rel="noreferrer">Main portfolio ↗</a></div><p className="text-sm text-[var(--muted)]">based in Barishal, Bangladesh.<br />Available for select commissions worldwide.</p></div><ContactForm /></div></div>;
}
