import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = { title: "About", description: "About Dhaka-based photographer TA Shanto and his approach to visual storytelling.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  return <div className="page-shell about-page"><header className="about-heading"><p>About the photographer</p><h1>Looking slowly.<br /><em>Keeping honestly.</em></h1></header><div className="about-layout"><div className="about-portrait"><Image src="/profile/tashanto-sample.png" alt="Sample portrait placeholder for TA Shanto" fill priority sizes="(max-width: 800px) 100vw, 42vw" /><small>Sample portrait — replace in /public/profile</small></div><div className="about-copy"><p className="lead">I’m Md Tanvir Ahamed Shanto, a photographer based in Dhaka. I photograph the quiet tension between people and place—often in available light, often while walking, always with curiosity.</p><p>My work is drawn to unguarded moments: rain shifting the rhythm of a street, the first light across a landscape, a face becoming still between words. I’m less interested in perfect scenes than in the feeling that remains after they have passed.</p><blockquote>Photography is my way of paying attention long enough for the ordinary to become specific.</blockquote><h2>Approach</h2><p>I work lightly and patiently, with respect for the people and places in front of the camera. The aim is not to over-direct life, but to recognize when light, gesture and atmosphere begin to tell the same story.</p><h2>Selected gear</h2><dl><div><dt>Camera</dt><dd>Sony α7 IV</dd></div><div><dt>Lenses</dt><dd>35mm F1.4 · 85mm F1.8 · 24–70mm F2.8</dd></div><div><dt>Based</dt><dd>Dhaka, Bangladesh · Available for select assignments</dd></div></dl><p className="developer-note">Away from the camera, I also build software. <Link href="https://tashanto.com" target="_blank">Developer portfolio ↗</Link></p></div></div></div>;
}
